// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: collector.proto

package collectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{0}
}

type GetVersionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit    string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// protocol_version is bumped on every incompatible change to this service;
	// the UI refuses to attach when it differs from its own compiled-in value.
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetVersionResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{2}
}

// Event mirrors a wails runtime event: a name plus an opaque JSON payload.
// Carrying the payload as JSON avoids a dedicated proto message per event
// type during the migration — the existing events are already JSON-serialised
// across the wails boundary — and can be tightened to typed messages later.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JsonPayload   []byte                 `protobuf:"bytes,2,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetJsonPayload() []byte {
	if x != nil {
		return x.JsonPayload
	}
	return nil
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// method is the exported app.App method name (e.g. "ProcessTracksByDay").
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// args is a JSON array whose elements decode into the method's parameters
	// in order. Empty/absent means a no-argument call.
	Args          []byte `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the JSON of the method's non-error return value, or null/empty
	// when it returns nothing or only an error.
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// error is the domain error message, empty on success.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShowUIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUIRequest) Reset() {
	*x = ShowUIRequest{}
	mi := &file_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUIRequest) ProtoMessage() {}

func (x *ShowUIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUIRequest.ProtoReflect.Descriptor instead.
func (*ShowUIRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{6}
}

type ShowUIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowUIResponse) Reset() {
	*x = ShowUIResponse{}
	mi := &file_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowUIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowUIResponse) ProtoMessage() {}

func (x *ShowUIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowUIResponse.ProtoReflect.Descriptor instead.
func (*ShowUIResponse) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{7}
}

var File_collector_proto protoreflect.FileDescriptor

const file_collector_proto_rawDesc = "" +
	"\n" +
	"\x0fcollector.proto\x12\x16hashpoint.collector.v1\"\x13\n" +
	"\x11GetVersionRequest\"\x90\x01\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\"\x0f\n" +
	"\rEventsRequest\">\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fjson_payload\x18\x02 \x01(\fR\vjsonPayload\";\n" +
	"\rInvokeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\">\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rShowUIRequest\"\x10\n" +
	"\x0eShowUIResponse2\xfb\x02\n" +
	"\x10CollectorService\x12c\n" +
	"\n" +
	"GetVersion\x12).hashpoint.collector.v1.GetVersionRequest\x1a*.hashpoint.collector.v1.GetVersionResponse\x12P\n" +
	"\x06Events\x12%.hashpoint.collector.v1.EventsRequest\x1a\x1d.hashpoint.collector.v1.Event0\x01\x12W\n" +
	"\x06Invoke\x12%.hashpoint.collector.v1.InvokeRequest\x1a&.hashpoint.collector.v1.InvokeResponse\x12W\n" +
	"\x06ShowUI\x12%.hashpoint.collector.v1.ShowUIRequest\x1a&.hashpoint.collector.v1.ShowUIResponseBDZBgithub.com/dusthoff/hashpoint/internal/ipc/collectorpb;collectorpbb\x06proto3"

var (
	file_collector_proto_rawDescOnce sync.Once
	file_collector_proto_rawDescData []byte
)

func file_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)))
	})
	return file_collector_proto_rawDescData
}

var file_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_collector_proto_goTypes = []any{
	(*GetVersionRequest)(nil),  // 0: hashpoint.collector.v1.GetVersionRequest
	(*GetVersionResponse)(nil), // 1: hashpoint.collector.v1.GetVersionResponse
	(*EventsRequest)(nil),      // 2: hashpoint.collector.v1.EventsRequest
	(*Event)(nil),              // 3: hashpoint.collector.v1.Event
	(*InvokeRequest)(nil),      // 4: hashpoint.collector.v1.InvokeRequest
	(*InvokeResponse)(nil),     // 5: hashpoint.collector.v1.InvokeResponse
	(*ShowUIRequest)(nil),      // 6: hashpoint.collector.v1.ShowUIRequest
	(*ShowUIResponse)(nil),     // 7: hashpoint.collector.v1.ShowUIResponse
}
var file_collector_proto_depIdxs = []int32{
	0, // 0: hashpoint.collector.v1.CollectorService.GetVersion:input_type -> hashpoint.collector.v1.GetVersionRequest
	2, // 1: hashpoint.collector.v1.CollectorService.Events:input_type -> hashpoint.collector.v1.EventsRequest
	4, // 2: hashpoint.collector.v1.CollectorService.Invoke:input_type -> hashpoint.collector.v1.InvokeRequest
	6, // 3: hashpoint.collector.v1.CollectorService.ShowUI:input_type -> hashpoint.collector.v1.ShowUIRequest
	1, // 4: hashpoint.collector.v1.CollectorService.GetVersion:output_type -> hashpoint.collector.v1.GetVersionResponse
	3, // 5: hashpoint.collector.v1.CollectorService.Events:output_type -> hashpoint.collector.v1.Event
	5, // 6: hashpoint.collector.v1.CollectorService.Invoke:output_type -> hashpoint.collector.v1.InvokeResponse
	7, // 7: hashpoint.collector.v1.CollectorService.ShowUI:output_type -> hashpoint.collector.v1.ShowUIResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collector_proto_init() }
func file_collector_proto_init() {
	if File_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_depIdxs,
		MessageInfos:      file_collector_proto_msgTypes,
	}.Build()
	File_collector_proto = out.File
	file_collector_proto_goTypes = nil
	file_collector_proto_depIdxs = nil
}
