// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: collector.proto

package collectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CollectorService_GetVersion_FullMethodName = "/hashpoint.collector.v1.CollectorService/GetVersion"
	CollectorService_Events_FullMethodName     = "/hashpoint.collector.v1.CollectorService/Events"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorServiceClient interface {
	// GetVersion returns the collector's build metadata and protocol version so
	// the UI can verify compatibility before issuing any domain calls. Both
	// binaries ship from one executable, but a stale UI spawned across an
	// in-place update must still detect a contract mismatch.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Events is the collector→UI push stream that replaces wails EventsEmit.
	// The UI re-emits each Event onto its local wails runtime so the frontend's
	// EventsOn handlers stay unchanged (ADR Anhang B).
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (CollectorService_EventsClient, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, CollectorService_GetVersion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (CollectorService_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], CollectorService_Events_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CollectorService_EventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type collectorServiceEventsClient struct {
	grpc.ClientStream
}

func (x *collectorServiceEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility
type CollectorServiceServer interface {
	// GetVersion returns the collector's build metadata and protocol version so
	// the UI can verify compatibility before issuing any domain calls. Both
	// binaries ship from one executable, but a stale UI spawned across an
	// in-place update must still detect a contract mismatch.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Events is the collector→UI push stream that replaces wails EventsEmit.
	// The UI re-emits each Event onto its local wails runtime so the frontend's
	// EventsOn handlers stay unchanged (ADR Anhang B).
	Events(*EventsRequest, CollectorService_EventsServer) error
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorServiceServer struct {
}

func (UnimplementedCollectorServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedCollectorServiceServer) Events(*EventsRequest, CollectorService_EventsServer) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServiceServer).Events(m, &collectorServiceEventsServer{stream})
}

type CollectorService_EventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type collectorServiceEventsServer struct {
	grpc.ServerStream
}

func (x *collectorServiceEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashpoint.collector.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _CollectorService_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _CollectorService_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collector.proto",
}
