// Code generated by cmd/genuiproxy. DO NOT EDIT.

package uiproxy

import (
	"github.com/dusthoff/hashpoint/internal/app"
	"github.com/dusthoff/hashpoint/internal/config"
	"github.com/dusthoff/hashpoint/internal/personio"
	"github.com/dusthoff/hashpoint/internal/plugin"
	"github.com/dusthoff/hashpoint/internal/storage"
)

func (a *App) CreateManualTagRange(p0 string, p1 string, p2 int64, p3 string) error {
	return a.call("CreateManualTagRange", []any{p0, p1, p2, p3}, nil)
}

func (a *App) CreateRule(p0 storage.Rule) (*storage.Rule, error) {
	var r0 *storage.Rule
	err := a.call("CreateRule", []any{p0}, &r0)
	return r0, err
}

func (a *App) CreateTag(p0 storage.Tag) (*storage.Tag, error) {
	var r0 *storage.Tag
	err := a.call("CreateTag", []any{p0}, &r0)
	return r0, err
}

func (a *App) DeleteRule(p0 int64) error {
	return a.call("DeleteRule", []any{p0}, nil)
}

func (a *App) DeleteTag(p0 int64) error {
	return a.call("DeleteTag", []any{p0}, nil)
}

func (a *App) DeleteTagBlock(p0 int64) error {
	return a.call("DeleteTagBlock", []any{p0}, nil)
}

func (a *App) DeleteTagBlocks(p0 []int64) (int, error) {
	var r0 int
	err := a.call("DeleteTagBlocks", []any{p0}, &r0)
	return r0, err
}

func (a *App) EntraLogin() error {
	return a.call("EntraLogin", nil, nil)
}

func (a *App) EntraLogout() error {
	return a.call("EntraLogout", nil, nil)
}

func (a *App) EntraStatus() app.EntraStatusResponse {
	var r0 app.EntraStatusResponse
	_ = a.call("EntraStatus", nil, &r0)
	return r0
}

func (a *App) FeedbackLogout() error {
	return a.call("FeedbackLogout", nil, nil)
}

func (a *App) FeedbackPollDeviceLogin() (*app.FeedbackPollResultDTO, error) {
	var r0 *app.FeedbackPollResultDTO
	err := a.call("FeedbackPollDeviceLogin", nil, &r0)
	return r0, err
}

func (a *App) FeedbackPreview(p0 app.FeedbackInputDTO) (string, error) {
	var r0 string
	err := a.call("FeedbackPreview", []any{p0}, &r0)
	return r0, err
}

func (a *App) FeedbackStartDeviceLogin() (*app.FeedbackDeviceCodeDTO, error) {
	var r0 *app.FeedbackDeviceCodeDTO
	err := a.call("FeedbackStartDeviceLogin", nil, &r0)
	return r0, err
}

func (a *App) FeedbackStatus() app.FeedbackStatusDTO {
	var r0 app.FeedbackStatusDTO
	_ = a.call("FeedbackStatus", nil, &r0)
	return r0
}

func (a *App) FeedbackSubmit(p0 app.FeedbackInputDTO) (*app.FeedbackSubmitResultDTO, error) {
	var r0 *app.FeedbackSubmitResultDTO
	err := a.call("FeedbackSubmit", []any{p0}, &r0)
	return r0, err
}

func (a *App) GetConfig() *config.Config {
	var r0 *config.Config
	_ = a.call("GetConfig", nil, &r0)
	return r0
}

func (a *App) GetUserDoc(p0 string) (string, error) {
	var r0 string
	err := a.call("GetUserDoc", []any{p0}, &r0)
	return r0, err
}

func (a *App) ImportPersonioDay(p0 string) (*personio.ImportResult, error) {
	var r0 *personio.ImportResult
	err := a.call("ImportPersonioDay", []any{p0}, &r0)
	return r0, err
}

func (a *App) IsManualTagActive() (int64, bool) {
	var r0 int64
	var r1 bool
	_ = a.callMulti("IsManualTagActive", nil, []any{&r0, &r1})
	return r0, r1
}

func (a *App) IsTrackingPaused() bool {
	var r0 bool
	_ = a.call("IsTrackingPaused", nil, &r0)
	return r0
}

func (a *App) ListPluginOrders() []plugin.Orders {
	var r0 []plugin.Orders
	_ = a.call("ListPluginOrders", nil, &r0)
	return r0
}

func (a *App) ListRules() ([]storage.Rule, error) {
	var r0 []storage.Rule
	err := a.call("ListRules", nil, &r0)
	return r0, err
}

func (a *App) ListTags() ([]storage.Tag, error) {
	var r0 []storage.Tag
	err := a.call("ListTags", nil, &r0)
	return r0, err
}

func (a *App) ListUserDocs() ([]app.UserDocPage, error) {
	var r0 []app.UserDocPage
	err := a.call("ListUserDocs", nil, &r0)
	return r0, err
}

func (a *App) LogFrontend(p0 string, p1 string, p2 map[string]any) {
	_ = a.call("LogFrontend", []any{p0, p1, p2}, nil)
}

func (a *App) OnCallDocDismiss(p0 int64) error {
	return a.call("OnCallDocDismiss", []any{p0}, nil)
}

func (a *App) OnCallDocGet(p0 int64) (*app.OnCallDocView, error) {
	var r0 *app.OnCallDocView
	err := a.call("OnCallDocGet", []any{p0}, &r0)
	return r0, err
}

func (a *App) OnCallDocList(p0 app.OnCallListFilter) ([]app.OnCallDocView, error) {
	var r0 []app.OnCallDocView
	err := a.call("OnCallDocList", []any{p0}, &r0)
	return r0, err
}

func (a *App) OnCallDocSave(p0 int64, p1 app.OnCallDocDraft) error {
	return a.call("OnCallDocSave", []any{p0, p1}, nil)
}

func (a *App) OnCallDocSubmit(p0 int64) error {
	return a.call("OnCallDocSubmit", []any{p0}, nil)
}

func (a *App) PauseTracking() {
	_ = a.call("PauseTracking", nil, nil)
}

func (a *App) PersonioCheck() app.PersonioSessionStatus {
	var r0 app.PersonioSessionStatus
	_ = a.call("PersonioCheck", nil, &r0)
	return r0
}

func (a *App) PersonioLogin() error {
	return a.call("PersonioLogin", nil, nil)
}

func (a *App) PersonioLogout() error {
	return a.call("PersonioLogout", nil, nil)
}

func (a *App) PersonioStatus() app.PersonioSessionStatus {
	var r0 app.PersonioSessionStatus
	_ = a.call("PersonioStatus", nil, &r0)
	return r0
}

func (a *App) PluginDeleteSecret(p0 string, p1 string) error {
	return a.call("PluginDeleteSecret", []any{p0, p1}, nil)
}

func (a *App) PluginGetConfig(p0 string) (app.PluginConfigView, error) {
	var r0 app.PluginConfigView
	err := a.call("PluginGetConfig", []any{p0}, &r0)
	return r0, err
}

func (a *App) PluginInstall(p0 string, p1 string) error {
	return a.call("PluginInstall", []any{p0, p1}, nil)
}

func (a *App) PluginList() ([]plugin.Info, error) {
	var r0 []plugin.Info
	err := a.call("PluginList", nil, &r0)
	return r0, err
}

func (a *App) PluginListAvailable() ([]plugin.AvailablePluginEntry, error) {
	var r0 []plugin.AvailablePluginEntry
	err := a.call("PluginListAvailable", nil, &r0)
	return r0, err
}

func (a *App) PluginRefreshTags(p0 string) (int, error) {
	var r0 int
	err := a.call("PluginRefreshTags", []any{p0}, &r0)
	return r0, err
}

func (a *App) PluginReload(p0 string) error {
	return a.call("PluginReload", []any{p0}, nil)
}

func (a *App) PluginSetConfig(p0 string, p1 map[string]string) error {
	return a.call("PluginSetConfig", []any{p0, p1}, nil)
}

func (a *App) PluginSetEnabled(p0 string, p1 bool) error {
	return a.call("PluginSetEnabled", []any{p0, p1}, nil)
}

func (a *App) PluginSetSecret(p0 string, p1 string, p2 string) error {
	return a.call("PluginSetSecret", []any{p0, p1, p2}, nil)
}

func (a *App) PluginUninstall(p0 string, p1 string) error {
	return a.call("PluginUninstall", []any{p0, p1}, nil)
}

func (a *App) PluginUpdate(p0 string, p1 string) error {
	return a.call("PluginUpdate", []any{p0, p1}, nil)
}

func (a *App) PreflightSyncDay(p0 string) (*personio.SyncPreflight, error) {
	var r0 *personio.SyncPreflight
	err := a.call("PreflightSyncDay", []any{p0}, &r0)
	return r0, err
}

func (a *App) ProcessTracksBetween(p0 string, p1 string) ([]storage.ProcessTrack, error) {
	var r0 []storage.ProcessTrack
	err := a.call("ProcessTracksBetween", []any{p0, p1}, &r0)
	return r0, err
}

func (a *App) ProcessTracksByDay(p0 string) ([]storage.ProcessTrack, error) {
	var r0 []storage.ProcessTrack
	err := a.call("ProcessTracksByDay", []any{p0}, &r0)
	return r0, err
}

func (a *App) QuickTagDismiss() {
	_ = a.call("QuickTagDismiss", nil, nil)
}

func (a *App) QuickTagSelect(p0 int64) error {
	return a.call("QuickTagSelect", []any{p0}, nil)
}

func (a *App) QuickTagSlots() ([]app.QuickTagSlot, error) {
	var r0 []app.QuickTagSlot
	err := a.call("QuickTagSlots", nil, &r0)
	return r0, err
}

func (a *App) ResizeTagBlock(p0 int64, p1 string, p2 string) error {
	return a.call("ResizeTagBlock", []any{p0, p1, p2}, nil)
}

func (a *App) ResumeTracking() {
	_ = a.call("ResumeTracking", nil, nil)
}

func (a *App) SaveConfig(p0 config.Config) error {
	return a.call("SaveConfig", []any{p0}, nil)
}

func (a *App) SetTagBlockDescription(p0 int64, p1 string) error {
	return a.call("SetTagBlockDescription", []any{p0, p1}, nil)
}

func (a *App) SetTagBlockTag(p0 int64, p1 int64) error {
	return a.call("SetTagBlockTag", []any{p0, p1}, nil)
}

func (a *App) StartManualTag(p0 int64, p1 string) error {
	return a.call("StartManualTag", []any{p0, p1}, nil)
}

func (a *App) StopManualTag() error {
	return a.call("StopManualTag", nil, nil)
}

func (a *App) SyncDay(p0 string) (*personio.Result, error) {
	var r0 *personio.Result
	err := a.call("SyncDay", []any{p0}, &r0)
	return r0, err
}

func (a *App) SyncRange(p0 string, p1 string) (*personio.Result, error) {
	var r0 *personio.Result
	err := a.call("SyncRange", []any{p0, p1}, &r0)
	return r0, err
}

func (a *App) TagBlocksBetween(p0 string, p1 string) ([]storage.TagBlock, error) {
	var r0 []storage.TagBlock
	err := a.call("TagBlocksBetween", []any{p0, p1}, &r0)
	return r0, err
}

func (a *App) TagBlocksByDay(p0 string) ([]storage.TagBlock, error) {
	var r0 []storage.TagBlock
	err := a.call("TagBlocksByDay", []any{p0}, &r0)
	return r0, err
}

func (a *App) TestRule(p0 storage.Rule, p1 string) ([]app.TestRuleResult, error) {
	var r0 []app.TestRuleResult
	err := a.call("TestRule", []any{p0, p1}, &r0)
	return r0, err
}

func (a *App) UpdateRule(p0 storage.Rule) error {
	return a.call("UpdateRule", []any{p0}, nil)
}

func (a *App) UpdateTag(p0 storage.Tag) error {
	return a.call("UpdateTag", []any{p0}, nil)
}

func (a *App) Version() app.VersionInfo {
	var r0 app.VersionInfo
	_ = a.call("Version", nil, &r0)
	return r0
}
