package personio

import (
	"strings"
	"testing"
	"time"

	"github.com/onesi/hashpoint/internal/storage"
)

func ptr[T any](v T) *T { return &v }

func mustEnd(t *testing.T, s string) *time.Time {
	t.Helper()
	v, err := time.Parse(time.RFC3339, s)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return &v
}

func TestBuildDayPeriods_PerProjectAndCommentBuckets(t *testing.T) {
	t.Parallel()

	parent := storage.Tag{
		ID:                1,
		Name:              "#projekta",
		PersonioProjectID: ptr("4711"),
		SyncToPersonio:    true,
	}
	subA := storage.Tag{
		ID:             2,
		ParentID:       ptr(int64(1)),
		Name:           "#frontend",
		Description:    ptr("Login"),
		SyncToPersonio: true,
	}
	subB := storage.Tag{
		ID:             3,
		ParentID:       ptr(int64(1)),
		Name:           "#meeting",
		SyncToPersonio: true,
	}
	tags := map[int64]storage.Tag{1: parent, 2: subA, 3: subB}

	day := time.Date(2026, 4, 25, 0, 0, 0, 0, time.UTC)
	blocks := []storage.FocusBlock{
		{
			ID: 1, ProcessName: "code", WindowTitle: "x",
			StartTime:   day.Add(9 * time.Hour),
			EndTime:     mustEnd(t, "2026-04-25T09:30:00Z"),
			TagID:       ptr(int64(2)),
			Description: ptr("Refactor LoginForm"),
		},
		{
			ID: 2, ProcessName: "teams", WindowTitle: "Standup",
			StartTime: day.Add(11 * time.Hour),
			EndTime:   mustEnd(t, "2026-04-25T11:30:00Z"),
			TagID:     ptr(int64(3)),
		},
		// Idle — must be skipped.
		{
			ID: 3, ProcessName: "x", WindowTitle: "y",
			StartTime: day.Add(12 * time.Hour),
			EndTime:   mustEnd(t, "2026-04-25T12:30:00Z"),
			IsIdle:    true,
			TagID:     ptr(int64(2)),
		},
	}

	periods := buildDayPeriods(blocks, tags)
	if len(periods) != 1 {
		t.Fatalf("expected 1 day bucket, got %d", len(periods))
	}
	for _, dp := range periods {
		if len(dp.list) != 2 {
			t.Fatalf("expected 2 distinct periods, got %d", len(dp.list))
		}
		for _, p := range dp.list {
			if p.PeriodType != "work" {
				t.Errorf("expected period_type=work, got %q", p.PeriodType)
			}
			if p.AutoGenerated {
				t.Errorf("auto_generated must be false for synced periods")
			}
			if p.ProjectID == nil || *p.ProjectID != 4711 {
				t.Errorf("project id missing on period: %+v", p)
			}
			// Times must be local-naive ISO (no timezone suffix).
			if strings.Contains(p.Start, "Z") || strings.Contains(p.Start, "+") {
				t.Errorf("start must be local-naive, got %q", p.Start)
			}
			if strings.Count(p.Start, ":") != 2 {
				t.Errorf("start must be HH:MM:SS shape, got %q", p.Start)
			}
		}
		// One of the comments must include the per-block description.
		joined := ""
		for _, p := range dp.list {
			joined += p.Comment + "|"
		}
		if !strings.Contains(joined, "Refactor LoginForm") {
			t.Errorf("expected description to flow into comment; got %q", joined)
		}
	}
}

func TestBuildDayPeriods_MergesOnlyConsecutiveRuns(t *testing.T) {
	t.Parallel()

	parent := storage.Tag{
		ID:                1,
		Name:              "#projekta",
		PersonioProjectID: ptr("4711"),
		SyncToPersonio:    true,
	}
	sub := storage.Tag{
		ID:             2,
		ParentID:       ptr(int64(1)),
		Name:           "#frontend",
		SyncToPersonio: true,
	}
	other := storage.Tag{
		ID:                3,
		Name:              "#projektb",
		PersonioProjectID: ptr("4712"),
		SyncToPersonio:    true,
	}
	tags := map[int64]storage.Tag{1: parent, 2: sub, 3: other}

	// Anchor at noon local so all subtest times stay on the same calendar
	// date regardless of the host timezone.
	day := time.Date(2026, 4, 25, 12, 0, 0, 0, time.Local)
	at := func(h, m int) time.Time {
		return day.Add(time.Duration(h-12)*time.Hour + time.Duration(m)*time.Minute)
	}
	end := func(h, m int) *time.Time { v := at(h, m); return &v }
	dateKey := day.Local().Format("2006-01-02")

	t.Run("contiguous same-tag+desc collapse to one period", func(t *testing.T) {
		blocks := []storage.FocusBlock{
			{ID: 1, ProcessName: "code", StartTime: at(9, 0), EndTime: end(9, 15), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, ProcessName: "chrome", StartTime: at(9, 15), EndTime: end(9, 45), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 3, ProcessName: "code", StartTime: at(9, 45), EndTime: end(10, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 1 {
			t.Fatalf("expected 1 merged period, got %+v", dp)
		}
		wantStart := blocks[0].StartTime.Local().Format("2006-01-02T15:04:05")
		wantEnd := blocks[len(blocks)-1].EndTime.Local().Format("2006-01-02T15:04:05")
		if dp.list[0].Start != wantStart {
			t.Errorf("merged period start = %q, want %q", dp.list[0].Start, wantStart)
		}
		if dp.list[0].End != wantEnd {
			t.Errorf("merged period end = %q, want %q", dp.list[0].End, wantEnd)
		}
		if got := len(dp.blockIDs); got != 3 {
			t.Errorf("expected 3 block ids on the merged period, got %d", got)
		}
	})

	t.Run("idle between same-tag blocks splits the run", func(t *testing.T) {
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(9, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, StartTime: at(9, 30), EndTime: end(10, 0), IsIdle: true},
			{ID: 3, StartTime: at(10, 0), EndTime: end(10, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 2 {
			t.Fatalf("expected 2 periods (idle splits the run), got %+v", dp)
		}
	})

	t.Run("different description breaks the run", func(t *testing.T) {
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(9, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, StartTime: at(9, 30), EndTime: end(10, 0), TagID: ptr(int64(2)), Description: ptr("Logout")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 2 {
			t.Fatalf("expected 2 periods (different descriptions), got %+v", dp)
		}
	})

	t.Run("different-tag block between same-tag blocks produces three periods", func(t *testing.T) {
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(9, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, StartTime: at(9, 30), EndTime: end(9, 45), TagID: ptr(int64(3))},
			{ID: 3, StartTime: at(9, 45), EndTime: end(10, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 3 {
			t.Fatalf("expected 3 periods (A | B | A), got %+v", dp)
		}
		// First A period must stop at 09:30 (before B starts), not run through
		// to 10:30 — that would mean B's slot got swallowed.
		firstAStart := blocks[0].StartTime.Local().Format("2006-01-02T15:04:05")
		firstAEnd := blocks[0].EndTime.Local().Format("2006-01-02T15:04:05")
		for _, p := range dp.list {
			if p.Start == firstAStart && p.End != firstAEnd {
				t.Errorf("first A period must end at %q (before B), got %q", firstAEnd, p.End)
			}
		}
	})

	t.Run("time gap with no intervening block still splits the run", func(t *testing.T) {
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(10, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
			// 1-hour gap with no recorded block — likely the laptop was closed.
			{ID: 2, StartTime: at(11, 0), EndTime: end(12, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 2 {
			t.Fatalf("expected 2 periods (time gap > tolerance), got %+v", dp)
		}
	})

	t.Run("morning run merges then lunch gap starts a fresh period", func(t *testing.T) {
		// Concrete example from the user: 09–10, 10–12, 13–15 with the same
		// tag/desc must collapse to 09–12 and 13–15 — never to a single 09–15
		// span that swallows the lunch break.
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(10, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, StartTime: at(10, 0), EndTime: end(12, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 3, StartTime: at(13, 0), EndTime: end(15, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 2 {
			t.Fatalf("expected 2 periods (09-12, 13-15), got %+v", dp)
		}
		want := [][2]string{
			{
				blocks[0].StartTime.Local().Format("2006-01-02T15:04:05"),
				blocks[1].EndTime.Local().Format("2006-01-02T15:04:05"),
			},
			{
				blocks[2].StartTime.Local().Format("2006-01-02T15:04:05"),
				blocks[2].EndTime.Local().Format("2006-01-02T15:04:05"),
			},
		}
		for i, p := range dp.list {
			if p.Start != want[i][0] || p.End != want[i][1] {
				t.Errorf("period[%d] = %s..%s, want %s..%s", i, p.Start, p.End, want[i][0], want[i][1])
			}
		}
	})

	t.Run("sub-second jitter still merges", func(t *testing.T) {
		// Tracker can produce a tiny gap when a focus event is delivered late;
		// staying inside the contiguity tolerance must still merge.
		blocks := []storage.FocusBlock{
			{ID: 1, StartTime: at(9, 0), EndTime: end(9, 30), TagID: ptr(int64(2)), Description: ptr("Login")},
			{ID: 2, StartTime: at(9, 30).Add(2 * time.Second), EndTime: end(10, 0), TagID: ptr(int64(2)), Description: ptr("Login")},
		}
		dp := buildDayPeriods(blocks, tags)[dateKey]
		if dp == nil || len(dp.list) != 1 {
			t.Fatalf("expected 1 merged period across 2s jitter, got %+v", dp)
		}
	})
}

func TestShouldSkip(t *testing.T) {
	t.Parallel()
	parent := storage.Tag{ID: 1, Name: "#x", PersonioProjectID: ptr("4711"), SyncToPersonio: true}
	noProject := storage.Tag{ID: 2, Name: "#y", SyncToPersonio: true}
	noSync := storage.Tag{ID: 3, Name: "#z", PersonioProjectID: ptr("4712"), SyncToPersonio: false}
	tags := map[int64]storage.Tag{1: parent, 2: noProject, 3: noSync}

	cases := []struct {
		name string
		b    storage.FocusBlock
		want bool
	}{
		{"open block", storage.FocusBlock{TagID: ptr(int64(1))}, true},
		{"untagged", storage.FocusBlock{EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, true},
		{"idle", storage.FocusBlock{IsIdle: true, TagID: ptr(int64(1)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, true},
		{"valid", storage.FocusBlock{TagID: ptr(int64(1)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, false},
		{"valid without project id", storage.FocusBlock{TagID: ptr(int64(2)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, false},
		{"sync_to_personio false", storage.FocusBlock{TagID: ptr(int64(3)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := shouldSkip(tc.b, tags); got != tc.want {
				t.Fatalf("got %v want %v", got, tc.want)
			}
		})
	}
}

func TestSession_XSRFTokenURLDecodes(t *testing.T) {
	t.Parallel()
	s := Session{
		Cookies: []SessionCookie{
			{Name: "PHPSESSID", Value: "abc"},
			{Name: "XSRF-TOKEN", Value: "abc%3D%3D"}, // url-encoded "abc=="
		},
	}
	if got, want := s.XSRFToken(), "abc=="; got != want {
		t.Errorf("XSRFToken=%q want %q", got, want)
	}
}

func TestTimecard_Trackable(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		state string
		want  bool
	}{
		{"trackable", true},
		{"open", true},
		{"non_trackable", false},
		{"locked", false},
		{"", false},
	} {
		got := Timecard{State: tc.state}.Trackable()
		if got != tc.want {
			t.Errorf("state=%q got=%v want=%v", tc.state, got, tc.want)
		}
	}
}
