package personio

import (
	"strings"
	"testing"
	"time"

	"github.com/onesi/hashpoint/internal/storage"
)

func ptr[T any](v T) *T { return &v }

func mustEnd(t *testing.T, s string) *time.Time {
	t.Helper()
	v, err := time.Parse(time.RFC3339, s)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return &v
}

func TestBuildDayPeriods_PerProjectAndCommentBuckets(t *testing.T) {
	t.Parallel()

	parent := storage.Tag{
		ID:                1,
		Name:              "#projekta",
		PersonioProjectID: ptr("4711"),
		SyncToPersonio:    true,
	}
	subA := storage.Tag{
		ID:             2,
		ParentID:       ptr(int64(1)),
		Name:           "#frontend",
		Description:    ptr("Login"),
		SyncToPersonio: true,
	}
	subB := storage.Tag{
		ID:             3,
		ParentID:       ptr(int64(1)),
		Name:           "#meeting",
		SyncToPersonio: true,
	}
	tags := map[int64]storage.Tag{1: parent, 2: subA, 3: subB}

	day := time.Date(2026, 4, 25, 0, 0, 0, 0, time.UTC)
	blocks := []storage.FocusBlock{
		{
			ID: 1, ProcessName: "code", WindowTitle: "x",
			StartTime:   day.Add(9 * time.Hour),
			EndTime:     mustEnd(t, "2026-04-25T09:30:00Z"),
			TagID:       ptr(int64(2)),
			Description: ptr("Refactor LoginForm"),
		},
		{
			ID: 2, ProcessName: "teams", WindowTitle: "Standup",
			StartTime: day.Add(11 * time.Hour),
			EndTime:   mustEnd(t, "2026-04-25T11:30:00Z"),
			TagID:     ptr(int64(3)),
		},
		// Idle — must be skipped.
		{
			ID: 3, ProcessName: "x", WindowTitle: "y",
			StartTime: day.Add(12 * time.Hour),
			EndTime:   mustEnd(t, "2026-04-25T12:30:00Z"),
			IsIdle:    true,
			TagID:     ptr(int64(2)),
		},
	}

	periods := buildDayPeriods(blocks, tags)
	if len(periods) != 1 {
		t.Fatalf("expected 1 day bucket, got %d", len(periods))
	}
	for _, dp := range periods {
		if len(dp.list) != 2 {
			t.Fatalf("expected 2 distinct periods, got %d", len(dp.list))
		}
		for _, p := range dp.list {
			if p.PeriodType != "work" {
				t.Errorf("expected period_type=work, got %q", p.PeriodType)
			}
			if p.AutoGenerated {
				t.Errorf("auto_generated must be false for synced periods")
			}
			if p.ProjectID == nil || *p.ProjectID != 4711 {
				t.Errorf("project id missing on period: %+v", p)
			}
			// Times must be local-naive ISO (no timezone suffix).
			if strings.Contains(p.Start, "Z") || strings.Contains(p.Start, "+") {
				t.Errorf("start must be local-naive, got %q", p.Start)
			}
			if strings.Count(p.Start, ":") != 2 {
				t.Errorf("start must be HH:MM:SS shape, got %q", p.Start)
			}
		}
		// One of the comments must include the per-block description.
		joined := ""
		for _, p := range dp.list {
			joined += p.Comment + "|"
		}
		if !strings.Contains(joined, "Refactor LoginForm") {
			t.Errorf("expected description to flow into comment; got %q", joined)
		}
	}
}

func TestShouldSkip(t *testing.T) {
	t.Parallel()
	parent := storage.Tag{ID: 1, Name: "#x", PersonioProjectID: ptr("4711"), SyncToPersonio: true}
	tags := map[int64]storage.Tag{1: parent}

	cases := []struct {
		name string
		b    storage.FocusBlock
		want bool
	}{
		{"open block", storage.FocusBlock{TagID: ptr(int64(1))}, true},
		{"untagged", storage.FocusBlock{EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, true},
		{"idle", storage.FocusBlock{IsIdle: true, TagID: ptr(int64(1)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, true},
		{"valid", storage.FocusBlock{TagID: ptr(int64(1)), EndTime: mustEnd(t, "2026-04-25T12:00:00Z")}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := shouldSkip(tc.b, tags); got != tc.want {
				t.Fatalf("got %v want %v", got, tc.want)
			}
		})
	}
}

func TestSession_XSRFTokenURLDecodes(t *testing.T) {
	t.Parallel()
	s := Session{
		Cookies: []SessionCookie{
			{Name: "PHPSESSID", Value: "abc"},
			{Name: "XSRF-TOKEN", Value: "abc%3D%3D"}, // url-encoded "abc=="
		},
	}
	if got, want := s.XSRFToken(), "abc=="; got != want {
		t.Errorf("XSRFToken=%q want %q", got, want)
	}
}

func TestTimecard_Trackable(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		state string
		want  bool
	}{
		{"trackable", true},
		{"open", true},
		{"non_trackable", false},
		{"locked", false},
		{"", false},
	} {
		got := Timecard{State: tc.state}.Trackable()
		if got != tc.want {
			t.Errorf("state=%q got=%v want=%v", tc.state, got, tc.want)
		}
	}
}
